"""Same-frame bilateral Dex3 calibration domain."""

from g1_dex3_tabletop.calibration.anchors import (
    BilateralAnchorDriftReport,
    evaluate_bilateral_anchor_drift,
)
from g1_dex3_tabletop.calibration.bundle import write_bilateral_calibration_bundle
from g1_dex3_tabletop.calibration.capture import (
    BilateralFrameEvidence,
    BilateralLiveBurstSource,
    select_bilateral_medoid,
)
from g1_dex3_tabletop.calibration.dataset import (
    merge_bilateral_datasets,
    sample_from_frame_evidence,
    target_observation_from_correspondences,
)
from g1_dex3_tabletop.calibration.design import (
    BilateralCaptureWaypoint,
    BilateralDesignCandidate,
    BilateralDesignConfig,
    BilateralDesignReport,
    BilateralDesignSelection,
    BilateralDesignStep,
    BilateralPoseDesignArtifact,
    build_repeated_anchor_schedule,
    linearize_design_candidate,
    select_bilateral_design,
)
from g1_dex3_tabletop.calibration.execution import (
    BilateralCollectionOrchestrator,
    BilateralCollectionResult,
    BilateralExecutionPlan,
    BilateralPlannedTransition,
    pose_sets_from_bilateral_plan,
)
from g1_dex3_tabletop.calibration.ferguson import (
    BilateralFergusonRecord,
    FergusonObservation,
    add_measured_color_frames,
    build_bilateral_optimizer_config,
    sample_to_ferguson_record,
)
from g1_dex3_tabletop.calibration.models import (
    BILATERAL_DATASET_SCHEMA_VERSION,
    BilateralCalibrationDataset,
    BilateralCalibrationSample,
    BilateralModelSpec,
    CameraFrameArtifact,
    TargetObservation,
)
from g1_dex3_tabletop.calibration.planning import (
    BilateralCalibrationPlanningRequest,
    BilateralFeasiblePose,
    BilateralIKResult,
    BilateralRoutePlanningRequest,
    BilateralRoutePlanningResult,
    BilateralVisibilityConfig,
    assemble_bilateral_planning_artifacts,
    build_bilateral_route_request,
)
from g1_dex3_tabletop.calibration.projection import (
    BilateralCalibrationProjection,
    BilateralObservabilityReport,
    target_parameter_names,
)
from g1_dex3_tabletop.calibration.session import (
    BILATERAL_SESSION_SCHEMA_VERSION,
    BILATERAL_SOURCE_ARTIFACTS,
    BilateralRawCaptureRecord,
    BilateralRawFrameRecord,
    BilateralSessionManifest,
    BilateralSessionStore,
)
from g1_dex3_tabletop.calibration.solver import (
    ROBOT_CALIBRATION_REVISION,
    BilateralSolverArtifacts,
    BilateralSolverResult,
    export_bilateral_solver_inputs,
    parse_ferguson_output,
    solve_bilateral_dataset,
    verify_robot_calibration_revision,
)
from g1_dex3_tabletop.calibration.validation import (
    BilateralBootstrapTrial,
    BilateralBootstrapValidation,
    BilateralCandidateValidation,
    BilateralFoldValidation,
    BilateralResidualMetrics,
    BilateralValidationConfig,
    BilateralValidationReport,
    evaluate_bilateral_solution,
    model_parameter_names,
    solution_physical_violations,
    validate_and_select_bilateral_model,
)

__all__ = [
    "BILATERAL_DATASET_SCHEMA_VERSION",
    "BILATERAL_SESSION_SCHEMA_VERSION",
    "BILATERAL_SOURCE_ARTIFACTS",
    "ROBOT_CALIBRATION_REVISION",
    "BilateralAnchorDriftReport",
    "BilateralBootstrapTrial",
    "BilateralBootstrapValidation",
    "BilateralCalibrationDataset",
    "BilateralCalibrationPlanningRequest",
    "BilateralCalibrationProjection",
    "BilateralCalibrationSample",
    "BilateralCandidateValidation",
    "BilateralCaptureWaypoint",
    "BilateralCollectionOrchestrator",
    "BilateralCollectionResult",
    "BilateralDesignCandidate",
    "BilateralDesignConfig",
    "BilateralDesignReport",
    "BilateralDesignSelection",
    "BilateralDesignStep",
    "BilateralExecutionPlan",
    "BilateralFeasiblePose",
    "BilateralFergusonRecord",
    "BilateralFoldValidation",
    "BilateralFrameEvidence",
    "BilateralIKResult",
    "BilateralLiveBurstSource",
    "BilateralModelSpec",
    "BilateralObservabilityReport",
    "BilateralPlannedTransition",
    "BilateralPoseDesignArtifact",
    "BilateralRawCaptureRecord",
    "BilateralRawFrameRecord",
    "BilateralResidualMetrics",
    "BilateralRoutePlanningRequest",
    "BilateralRoutePlanningResult",
    "BilateralSessionManifest",
    "BilateralSessionStore",
    "BilateralSolverArtifacts",
    "BilateralSolverResult",
    "BilateralValidationConfig",
    "BilateralValidationReport",
    "BilateralVisibilityConfig",
    "CameraFrameArtifact",
    "FergusonObservation",
    "TargetObservation",
    "add_measured_color_frames",
    "assemble_bilateral_planning_artifacts",
    "build_bilateral_optimizer_config",
    "build_bilateral_route_request",
    "build_repeated_anchor_schedule",
    "evaluate_bilateral_anchor_drift",
    "evaluate_bilateral_solution",
    "export_bilateral_solver_inputs",
    "linearize_design_candidate",
    "merge_bilateral_datasets",
    "model_parameter_names",
    "parse_ferguson_output",
    "pose_sets_from_bilateral_plan",
    "sample_from_frame_evidence",
    "sample_to_ferguson_record",
    "select_bilateral_design",
    "select_bilateral_medoid",
    "solution_physical_violations",
    "solve_bilateral_dataset",
    "target_observation_from_correspondences",
    "target_parameter_names",
    "validate_and_select_bilateral_model",
    "verify_robot_calibration_revision",
    "write_bilateral_calibration_bundle",
]
