"""Dedicated execution of one frozen same-frame bilateral calibration route.

Importing this module is inert. The command performs a read-only validation
and asks the isolated CuRobo worker for only the live Ready-to-anchor adapter,
then creates Unitree publishers only after SPACE. The long calibration core is
never regenerated by the hardware process.
"""

from __future__ import annotations

import json
import time
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path

import cv2
import numpy as np
from aprilcube import CorrespondenceDetector

from g1_aprilcube_calibration.clock import SystemClock
from g1_aprilcube_calibration.executor_driver import (
    ExecutorControlDriver,
    SynchronizedPoseExecutor,
)
from g1_aprilcube_calibration.executor_state_machine import ExecutorState, PoseExecutor
from g1_aprilcube_calibration.joint_map import (
    LEFT_ARM_INDICES,
    RIGHT_ARM_INDICES,
    arm_indices,
    opposite_arm,
)
from g1_aprilcube_calibration.live_capture import LiveBurstConfig
from g1_aprilcube_calibration.models import utc_now_iso
from g1_aprilcube_calibration.process_lock import CommandOwnerLock
from g1_aprilcube_calibration.quality import (
    CameraIntrinsics,
    PoseQualityEvaluator,
    QualityGrade,
    QualityThresholds,
)
from g1_aprilcube_calibration.readiness import StateSampleBuffer
from g1_aprilcube_calibration.ros.camera_adapter import ROSCameraSubscriber
from g1_aprilcube_calibration.session_store import IsolatedSessionStore
from g1_aprilcube_calibration.transports.unitree_arm_sdk import (
    UnitreeArmSDKTransport,
    UnitreeLowStateObserver,
)
from g1_aprilcube_calibration.transports.unitree_dex3 import (
    UnitreeDex3PostureController,
    UnitreeDex3StateObserver,
)
from g1_aprilcube_calibration.urdf_model import URDFModel
from g1_dex3_tabletop.calibration import (
    BILATERAL_SOURCE_ARTIFACTS,
    BilateralCollectionOrchestrator,
    BilateralExecutionPlan,
    BilateralLiveBurstSource,
    BilateralPoseDesignArtifact,
    BilateralSessionStore,
    CameraFrameArtifact,
    pose_sets_from_bilateral_plan,
)
from g1_dex3_tabletop.calibration_candidates import camera_info_from_hardware
from g1_dex3_tabletop.hardware_calibration import (
    _command_validated_finger_posture,
    _execute_stage,
    _snapshot,
    _stage_executor,
    _stage_trajectory,
)
from g1_dex3_tabletop.hardware_config import (
    dex3_config,
    executor_config,
    gravity_feedforward,
    load_hardware,
    recording_configs,
    resolve_hardware_path,
    transport_config,
    watchdog,
)
from g1_dex3_tabletop.hardware_stack import (
    _command_bound_snapshot,
    _install_plan_at_current_boundary,
)
from g1_dex3_tabletop.hardware_tabletop import (
    MOTION_ACK,
    _finger_heartbeat,
    _wait_for_activation,
    _wait_for_hands,
    _wait_for_space_with_preview,
    _wait_for_state,
    _wait_ready,
)
from g1_dex3_tabletop.persistent_planner import PersistentTabletopPlanner
from g1_dex3_tabletop.planning.contracts import (
    BilateralCalibrationAdapterPlan,
    BilateralCalibrationAdapterRequest,
    atomic_write_json,
)
from g1_dex3_tabletop.planning.dex3_handedness import (
    dex3_empty_close_reference,
    dex3_execution_profile,
)
from g1_dex3_tabletop.planning.g1_model import validate_dex3_finger_targets
from g1_dex3_tabletop.raw_episode_recording import (
    STANDING_CALIBRATION_PROFILE_NAME,
    STANDING_CALIBRATION_TOPICS,
    RawEpisodeRecorder,
)

ROOT = Path(__file__).resolve().parents[2]
_SIDES = ("left", "right")


def _session_name() -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"dex3_bilateral_curobo_{stamp}"


def validate_frozen_bilateral_inputs(
    *,
    design: BilateralPoseDesignArtifact,
    plan: BilateralExecutionPlan,
    model: URDFModel,
    camera_frames: CameraFrameArtifact,
    expected_camera,
) -> dict:
    """Validate all immutable route/model/camera bindings without hardware writes."""

    plan.validate_design(design)
    certificate = plan.self_clearance_certificate
    if (
        float(certificate["hard_clearance_m"]) < 0.010
        or float(certificate["minimum_clearance_m"]) < 0.010 - 1e-6
        or float(certificate.get("preexisting_clearance_maximum_degradation_m", -1.0)) != 0.0
    ):
        raise ValueError(
            "bilateral core requires strict 10mm clearance with no reference exception; "
            "use the recertified pose-design/execution-plan pair"
        )
    if plan.robot_model != model.name:
        raise ValueError("bilateral execution plan belongs to a different robot model")
    if plan.urdf_sha256 != model.sha256:
        raise ValueError("bilateral execution plan belongs to a different robot URDF")
    if camera_frames.camera_serial != expected_camera.serial_number:
        raise ValueError("camera-frame artifact belongs to a different RealSense serial")
    if camera_frames.optical_frame != expected_camera.frame_id:
        raise ValueError("camera-frame artifact optical frame differs from CameraInfo")
    if camera_frames.urdf_parent_link not in model.links:
        raise ValueError("camera-frame artifact parent link is absent from the robot URDF")
    return pose_sets_from_bilateral_plan(design, plan)


def _hand_posture_error_rad(hands, target_q_rad_by_arm) -> float:
    return max(
        float(
            np.max(
                np.abs(np.asarray(hands.left.position) - np.asarray(target_q_rad_by_arm["left"]))
            )
        ),
        float(
            np.max(
                np.abs(np.asarray(hands.right.position) - np.asarray(target_q_rad_by_arm["right"]))
            )
        ),
    )


def _wait_for_bilateral_visibility(
    rclpy,
    node,
    camera,
    *,
    detectors,
    evaluators,
    expected_camera,
    timeout_s: float,
):
    deadline = time.monotonic() + timeout_s
    last = "no rectified image"
    while time.monotonic() < deadline:
        rclpy.spin_once(node, timeout_sec=0.02)
        frame = camera.frames.latest
        if frame is None:
            continue
        if frame.camera_info.profile_sha256 != expected_camera.profile_sha256:
            raise ValueError("live CameraInfo differs from the frozen hardware profile")
        intrinsics = CameraIntrinsics(
            frame.camera_info.rectified_camera_matrix,
            frame.camera_info.d,
        )
        results = {side: detectors[side].detect(frame.image_bgr) for side in _SIDES}
        reports = {
            side: evaluators[side].evaluate(
                results[side],
                intrinsics=intrinsics,
                history=(),
            )
            for side in _SIDES
        }
        failures = []
        for side in _SIDES:
            if not results[side].valid:
                failures.append(f"{side} target is not detected unambiguously")
            elif reports[side].grade is QualityGrade.RED:
                failures.append(
                    f"{side} quality is red: " + "; ".join(reports[side].hard_failures)
                )
        if not failures:
            return frame, results, reports
        last = "; ".join(failures)
    raise RuntimeError("timed out waiting for both hand targets: " + last)


def _wait_for_camera_profile(rclpy, node, camera, *, expected_camera, timeout_s: float):
    """Require the frozen camera stream without requiring Ready marker visibility."""

    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        rclpy.spin_once(node, timeout_sec=0.02)
        frame = camera.frames.latest
        if frame is None:
            continue
        if frame.camera_info.profile_sha256 != expected_camera.profile_sha256:
            raise ValueError("live CameraInfo differs from the frozen hardware profile")
        return frame
    raise RuntimeError("timed out waiting for the frozen rectified camera stream")


def _render_bilateral_preview(image, detections, reports, *, footer: tuple[str, ...]):
    canvas = np.asarray(image).copy()
    colors = {"left": (255, 180, 0), "right": (0, 220, 255)}
    for side in _SIDES:
        color = colors[side]
        for observation in detections[side].observations:
            corners = np.rint(observation.image_corners_px).astype(np.int32)
            cv2.polylines(canvas, [corners], True, color, 3, cv2.LINE_AA)
        cv2.putText(
            canvas,
            f"{side.upper()}: {reports[side].grade.value.upper()}",
            (24, 42 if side == "left" else 76),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            color,
            2,
            cv2.LINE_AA,
        )
    y = canvas.shape[0] - 24 * len(footer)
    for line in footer:
        cv2.putText(
            canvas,
            line,
            (24, y),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.58,
            (255, 255, 255),
            2,
            cv2.LINE_AA,
        )
        y += 24
    return canvas


def _stop_driver(driver, guard) -> None:
    driver.close()
    driver.check()
    guard.pulse()


def _plan_owned_adapter(
    *,
    synchronized,
    driver,
    planner,
    preflight_request: BilateralCalibrationAdapterRequest,
    held_hands,
    model: URDFModel,
    work_directory: Path,
):
    """Reuse the stack's exact-command planning and installation boundary."""

    driver.check()
    reference_state, command_q14 = synchronized.observe_dual_arm_control_input()
    snapshot = _command_bound_snapshot(reference_state, held_hands, command_q14)
    request = replace(preflight_request, snapshot=snapshot)
    request_path = work_directory / "owned_adapter_request.json"
    plan_path = work_directory / "owned_adapter_plan.json"
    request.write_json(request_path)
    planner.request(
        "plan-bilateral-calibration-adapter",
        request_path=request_path,
        output_path=plan_path,
        control_check=driver.check,
        timeout_s=600.0,
    )
    driver.check()
    adapter = BilateralCalibrationAdapterPlan.from_json(plan_path)
    if adapter.request_sha256 != request.content_sha256:
        raise ValueError("owned bilateral adapter plan/request binding changed")
    anchor_q29 = np.asarray(request.anchor_q29_rad)
    expected_anchor = anchor_q29[np.asarray((*LEFT_ARM_INDICES, *RIGHT_ARM_INDICES))]
    if not np.allclose(adapter.anchor_q14_rad, expected_anchor, atol=1e-9, rtol=0):
        raise ValueError("owned adapter endpoint differs from the reusable anchor")
    right_outbound = _stage_trajectory(adapter.preparation.right_outbound)
    _install_plan_at_current_boundary(
        synchronized,
        arm="right",
        trajectories=(right_outbound,),
        plan_sha256=adapter.content_sha256,
        validated_reference_state=reference_state,
        model=model,
    )
    return request, adapter, right_outbound


def run_collect_bilateral_calibration(args) -> int:
    """Execute and record one exact, prevalidated bilateral calibration route."""

    if args.confirm != MOTION_ACK:
        raise ValueError(f"--confirm must equal exactly: {MOTION_ACK}")
    if args.maximum_capture_attempts < 1:
        raise ValueError("--maximum-capture-attempts must be positive")

    hardware_path = args.hardware_config.resolve()
    hardware = load_hardware(hardware_path)
    design = BilateralPoseDesignArtifact.from_json(args.pose_design)
    plan = BilateralExecutionPlan.from_json(args.execution_plan)
    camera_frames = CameraFrameArtifact.from_json(args.camera_frames)
    model = URDFModel(resolve_hardware_path(hardware_path, hardware["robot"]["urdf"]))
    expected_camera = camera_info_from_hardware(hardware)
    pose_sets = validate_frozen_bilateral_inputs(
        design=design,
        plan=plan,
        model=model,
        camera_frames=camera_frames,
        expected_camera=expected_camera,
    )
    initial_arm = plan.transitions[0].arm
    recording, pairing = recording_configs(hardware_path)
    recording = replace(recording, calibration_arm=initial_arm)
    control_config, rate_hz = executor_config(hardware_path)
    dex_config_value = dex3_config(
        hardware_path,
        interface=args.network_interface,
        domain_id=args.domain_id,
    )
    commissioned_command_q = {side: dex3_execution_profile(side)[1] for side in _SIDES}
    commissioned_model_q = {side: dex3_empty_close_reference(side)[0] for side in _SIDES}
    planned_command_error = max(
        float(
            np.max(
                np.abs(
                    np.asarray(plan.commanded_dex3_joint_positions_rad[side])
                    - np.asarray(commissioned_command_q[side])
                )
            )
        )
        for side in _SIDES
    )
    planned_model_error = max(
        float(
            np.max(
                np.abs(
                    np.asarray(plan.modeled_dex3_joint_positions_rad[side])
                    - np.asarray(commissioned_model_q[side])
                )
            )
        )
        for side in _SIDES
    )
    if max(planned_command_error, planned_model_error) > 1e-9:
        raise ValueError(
            "bilateral execution plan does not use the commissioned fixed-close "
            "command and empty-close collision model"
        )
    thresholds = QualityThresholds.from_yaml(args.quality_config)
    detectors = {
        "left": CorrespondenceDetector(args.left_target_config),
        "right": CorrespondenceDetector(args.right_target_config),
    }
    if detectors["left"].valid_ids & detectors["right"].valid_ids:
        raise ValueError("left and right target artifacts must use disjoint marker IDs")
    evaluators = {side: PoseQualityEvaluator(thresholds) for side in _SIDES}

    session_directory = (
        (ROOT / "sessions" / _session_name()).resolve()
        if args.session_directory is None
        else args.session_directory.resolve()
    )
    if session_directory.exists():
        raise FileExistsError(f"session directory already exists: {session_directory}")
    work_directory = ROOT / "work" / f"{session_directory.name}_collection"
    if work_directory.exists():
        raise FileExistsError(f"collection work directory already exists: {work_directory}")
    work_directory.mkdir(parents=True)
    status_path = work_directory / "status.json"
    status = {"status": "preflight", "commands_robot": False}

    paths = {
        "camera_frames.json": args.camera_frames.resolve(),
        "capture_quality.yaml": args.quality_config.resolve(),
        "execution_plan.json": args.execution_plan.resolve(),
        "left_target.json": args.left_target_config.resolve(),
        "pose_design.json": args.pose_design.resolve(),
        "right_target.json": args.right_target_config.resolve(),
        "robot.urdf": model.path,
    }

    command_lock = CommandOwnerLock(args.lock_file)
    camera = observer = dex_observer = transport = dex_controller = None
    guard = synchronized = driver = isolated_store = planner = None
    raw_recorder = None
    command_lock.acquire()
    try:
        try:
            import rclpy
        except ImportError as error:
            raise RuntimeError("rclpy unavailable; use ./tools/g1_tabletop_hardware.sh") from error
        rclpy.init(args=None)
        node = rclpy.create_node("g1_dex3_bilateral_calibration")
        try:
            camera = ROSCameraSubscriber(
                node,
                image_topic=hardware["ros"]["image_topic"],
                camera_info_topic=hardware["ros"]["camera_info_topic"],
                camera_name=hardware["camera"]["name"],
                serial_number=hardware["camera"]["serial_number"],
                reliability=hardware["ros"]["camera_reliability"],
                qos_depth=int(hardware["ros"]["camera_qos_depth"]),
                maximum_frames=30,
            )
            states = StateSampleBuffer()
            transport_cfg = transport_config(
                hardware_path,
                interface=args.network_interface,
                domain_id=args.domain_id,
            )
            observer = UnitreeLowStateObserver(transport_cfg, on_sample=states.add)
            _wait_for_state(observer)
            dex_observer = UnitreeDex3StateObserver(
                dex_config_value,
                initialize_factory=False,
            )
            hands = _wait_for_hands(dex_observer)
            activation = _wait_for_activation(
                observer,
                states,
                pose_sets[initial_arm],
                recording,
                timeout_s=8.0,
            )
            preflight_snapshot = _snapshot(activation.reference_state, hands)
            anchor_q29 = np.asarray(
                design.waypoint_joint_positions_rad[design.schedule[0].candidate_id],
                dtype=np.float64,
            )
            _wait_for_camera_profile(
                rclpy,
                node,
                camera,
                expected_camera=expected_camera,
                timeout_s=args.camera_timeout_s,
            )
            adapter_request = BilateralCalibrationAdapterRequest(
                execution_plan_sha256=plan.content_sha256,
                robot_model=plan.robot_model,
                urdf_sha256=plan.urdf_sha256,
                snapshot=preflight_snapshot,
                anchor_q29_rad=tuple(anchor_q29),
                core_transitions=tuple(item.to_dict() for item in plan.transitions),
                joint_position_offsets_rad=plan.joint_position_offsets_rad,
                left_close_command_q_rad=plan.commanded_dex3_joint_positions_rad["left"],
                right_close_command_q_rad=plan.commanded_dex3_joint_positions_rad["right"],
                left_close_model_q_rad=plan.modeled_dex3_joint_positions_rad["left"],
                right_close_model_q_rad=plan.modeled_dex3_joint_positions_rad["right"],
                random_seed=args.seed,
            )
            adapter_request_path = work_directory / "adapter_request.json"
            adapter_plan_path = work_directory / "adapter_plan.json"
            adapter_request.write_json(adapter_request_path)
            validate_dex3_finger_targets(
                left_q_rad=preflight_snapshot.left_dex3_q_rad,
                right_q_rad=preflight_snapshot.right_dex3_q_rad,
                label="starting-posture restoration target",
            )
            print(
                "READ-ONLY CUROBO ADAPTER — planning only this run's measured "
                "Ready-to-fixed-anchor boundary; reusable calibration core unchanged; "
                "NO MOTION",
                flush=True,
            )
            planner = PersistentTabletopPlanner(
                executable=ROOT / ".venv-planner/bin/g1-curobo-worker",
                log_path=work_directory / "adapter_plan.planner.log",
            )
            planner.start()
            planner.request(
                "plan-bilateral-calibration-adapter",
                request_path=adapter_request_path,
                output_path=adapter_plan_path,
                timeout_s=600.0,
            )
            adapter = BilateralCalibrationAdapterPlan.from_json(adapter_plan_path)
            if adapter.request_sha256 != adapter_request.content_sha256:
                raise ValueError("bilateral adapter plan/request binding changed")
            planned_anchor_error = float(
                np.max(
                    np.abs(
                        np.asarray(adapter.anchor_q14_rad)
                        - np.concatenate(
                            (
                                anchor_q29[np.asarray(LEFT_ARM_INDICES)],
                                anchor_q29[np.asarray(RIGHT_ARM_INDICES)],
                            )
                        )
                    )
                )
            )
            if planned_anchor_error > 1e-9:
                raise ValueError("live adapter endpoint differs from the reusable anchor")
            paths.update(
                {
                    "adapter_request.json": adapter_request_path,
                    "adapter_plan.json": adapter_plan_path,
                }
            )
            if set(paths) != BILATERAL_SOURCE_ARTIFACTS:
                raise AssertionError("bilateral source path contract changed")
            source_artifacts = {name: path.read_bytes() for name, path in paths.items()}
            isolated_store = IsolatedSessionStore(
                session_directory,
                poll_interval_s=1.0 / rate_hz,
                store_factory=BilateralSessionStore,
            )
            isolated_store.start()
            raw_recorder = RawEpisodeRecorder(
                work_directory / "raw_episode",
                repository=ROOT,
                topics=STANDING_CALIBRATION_TOPICS,
                profile_name=STANDING_CALIBRATION_PROFILE_NAME,
            )
            raw_recorder.start()
            # Keep the exact runtime settings beside the bag, including failed
            # takeovers that never reach a calibration capture.
            atomic_write_json(
                raw_recorder.episode_directory / "hardware_configuration.json", hardware
            )
            print(
                "RAW RECORDING READY — arm_sdk, LowState, and both Dex3 state/command "
                "streams subscribed before SPACE; recording through control cleanup",
                flush=True,
            )
            capture_count = sum(item.capturable for item in design.schedule)
            print(
                f"READ-ONLY BILATERAL PREFLIGHT PASSED — "
                f"{capture_count} same-frame captures, "
                f"{len(plan.transitions)} reusable core trajectories, live reversible "
                f"adapter planned in {adapter.planner_provenance['elapsed_s']:.1f}s; "
                "NO MOTION",
                flush=True,
            )
            _wait_for_space_with_preview(
                rclpy,
                node,
                camera,
                arm="both",
                no_window=args.no_window,
                prompt=(
                    "START BILATERAL CALIBRATION — G1 in normal Ready under the "
                    "load-bearing harness; complete two-arm route clear. CuRobo will "
                    "move to shoulder clearance, close both hands, and then move to "
                    "the both-visible anchor. Press SPACE once: "
                ),
                overlay="READ-ONLY - SPACE starts live-adapted bilateral route",
            )
            changed = [
                name for name, path in paths.items() if path.read_bytes() != source_artifacts[name]
            ]
            if changed:
                raise RuntimeError(
                    "bilateral source artifacts changed after preflight: " + ", ".join(changed)
                )
            latest_activation = _wait_for_activation(
                observer,
                states,
                pose_sets[initial_arm],
                recording,
                timeout_s=8.0,
            )
            latest_hands = _wait_for_hands(dex_observer)
            latest_snapshot = _snapshot(latest_activation.reference_state, latest_hands)
            latest_ready_error = float(
                np.max(
                    np.abs(
                        np.asarray(latest_snapshot.measured_q29_rad)
                        - np.asarray(preflight_snapshot.measured_q29_rad)
                    )
                )
            )
            latest_hand_error = max(
                float(
                    np.max(
                        np.abs(
                            np.asarray(getattr(latest_snapshot, f"{side}_dex3_q_rad"))
                            - np.asarray(getattr(preflight_snapshot, f"{side}_dex3_q_rad"))
                        )
                    )
                )
                for side in _SIDES
            )
            if latest_ready_error > control_config.activation_position_tolerance_rad:
                raise RuntimeError("robot changed after bilateral preflight; no publisher created")
            if latest_hand_error > dex_config_value.posture_position_tolerance_rad:
                raise RuntimeError("Dex3 posture changed after preflight; no publisher created")

            gravity = gravity_feedforward(
                hardware_path,
                latest_activation.reference_state.position,
            )
            guard = watchdog(
                hardware_path,
                host=args.pc2_host,
                ssh_identity=args.pc2_ssh_identity,
                initial_fsm_id=int(hardware["control"]["required_regular_fsm_id"]),
                restore_seated=False,
            )
            raw_recorder.check()
            transport = UnitreeArmSDKTransport(transport_cfg, observer=observer)
            observer = None
            dex_controller = UnitreeDex3PostureController(
                dex_config_value,
                observer=dex_observer,
            )
            dex_observer = None
            # Match the commissioned standing collector: each of the three
            # SDK publisher Init calls sleeps 0.2 s. Finish them before arming
            # the 0.5 s heartbeat deadline; constructors publish no commands.
            guard.start()
            held_hands = dex_controller.acquire_measured_hold(safety_heartbeat=guard.pulse)

            q29 = np.asarray(latest_activation.reference_state.position, dtype=np.float64).copy()
            q14 = np.concatenate(
                (q29[np.asarray(LEFT_ARM_INDICES)], q29[np.asarray(RIGHT_ARM_INDICES)])
            )
            synchronized, driver = _stage_executor(
                arm="right",
                trajectory=None,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=True,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            print(
                "CONTROL ACQUIRED — refreshing the reversible adapter from both exact "
                "held arm commands; fixed calibration core retained",
                flush=True,
            )
            adapter_request, adapter, right_outbound = _plan_owned_adapter(
                synchronized=synchronized,
                driver=driver,
                planner=planner,
                preflight_request=adapter_request,
                held_hands=held_hands,
                model=model,
                work_directory=work_directory,
            )
            q29 = np.asarray(adapter_request.snapshot.measured_q29_rad).copy()
            q14 = synchronized.dual_arm_command_q
            # Preserve preflight evidence in work/. The immutable session must
            # contain the adapter actually installed after ownership.
            source_artifacts = {
                **source_artifacts,
                "adapter_request.json": (
                    work_directory / "owned_adapter_request.json"
                ).read_bytes(),
                "adapter_plan.json": (work_directory / "owned_adapter_plan.json").read_bytes(),
            }
            isolated_store.set_health_check(driver.check)
            isolated_store.create(
                session_id=session_directory.name,
                created_at_utc=utc_now_iso(),
                day_group_id=args.day_group_id or datetime.now(timezone.utc).date().isoformat(),
                camera_info=expected_camera,
                camera_frames=camera_frames,
                pose_design_sha256=design.content_sha256,
                execution_plan_sha256=plan.content_sha256,
                source_artifacts=source_artifacts,
                pairing_config=pairing,
                recording_gate_config=recording,
                provenance={
                    "command": "g1-tabletop collect-bilateral-calibration",
                    "route_policy": "owned_command_adapter_reusable_anchor_core_exact_reverse",
                    "starting_finger_policy": "restore_measured_hold_acquisition_posture",
                    "capture_policy": "same_image_left_and_right_targets",
                    "yellow_policy": "accepted_with_recorded_quality_evidence",
                    "maximum_capture_attempts": args.maximum_capture_attempts,
                    "initial_arm": initial_arm,
                    "ready_error_rad": latest_ready_error,
                    "dex3_posture_error_rad": latest_hand_error,
                    "planned_dex3_command_error_rad": planned_command_error,
                    "planned_dex3_model_error_rad": planned_model_error,
                    "adapter_request_sha256": adapter_request.content_sha256,
                    "adapter_plan_sha256": adapter.content_sha256,
                    "adapter_locked_joint_error_rad": (
                        adapter.maximum_locked_joint_error_rad_observed
                    ),
                    "adapter_live_core_minimum_clearance_margin_m": (
                        adapter.live_core_self_clearance_certificate[
                            "minimum_margin_to_required_clearance_m"
                        ]
                    ),
                },
            )
            _execute_stage(
                synchronized,
                driver,
                right_outbound,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(RIGHT_ARM_INDICES)] = np.asarray(right_outbound.command_q_rad[-1])
            q14[7:] = np.asarray(right_outbound.command_q_rad[-1])
            _stop_driver(driver, guard)
            driver = None

            left_outbound = _stage_trajectory(adapter.preparation.left_outbound)
            synchronized, driver = _stage_executor(
                arm="left",
                trajectory=left_outbound,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                left_outbound,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(LEFT_ARM_INDICES)] = np.asarray(left_outbound.command_q_rad[-1])
            q14[:7] = np.asarray(left_outbound.command_q_rad[-1])
            settled = _command_validated_finger_posture(
                synchronized=synchronized,
                driver=driver,
                controller=dex_controller,
                planner=planner,
                joint_position_offsets_rad=plan.joint_position_offsets_rad,
                body_tolerance_rad=control_config.ownership_transition_position_tolerance_rad,
                hand_tolerance_rad=dex_config_value.posture_position_tolerance_rad,
                artifact_directory=session_directory / "runtime",
                phase="loaded_close",
                left_target_q_rad=plan.commanded_dex3_joint_positions_rad["left"],
                right_target_q_rad=plan.commanded_dex3_joint_positions_rad["right"],
                left_acceptance_q_rad=plan.modeled_dex3_joint_positions_rad["left"],
                right_acceptance_q_rad=plan.modeled_dex3_joint_positions_rad["right"],
                label="commissioned bilateral full-close calibration posture",
            )
            close_error = _hand_posture_error_rad(
                settled,
                plan.modeled_dex3_joint_positions_rad,
            )
            if close_error > dex_config_value.posture_position_tolerance_rad:
                raise RuntimeError(
                    f"settled Dex3 close differs from its commissioned model by "
                    f"{close_error:.4f}rad"
                )
            print(
                "DEX3 CLOSE READY — both hands verified at shoulder clearance",
                flush=True,
            )
            _stop_driver(driver, guard)
            driver = None

            right_anchor_outbound = _stage_trajectory(adapter.right_anchor_outbound)
            synchronized, driver = _stage_executor(
                arm="right",
                trajectory=right_anchor_outbound,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                right_anchor_outbound,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(RIGHT_ARM_INDICES)] = np.asarray(
                right_anchor_outbound.command_q_rad[-1]
            )
            q14[7:] = np.asarray(right_anchor_outbound.command_q_rad[-1])
            _stop_driver(driver, guard)
            driver = None

            left_anchor_outbound = _stage_trajectory(adapter.left_anchor_outbound)
            synchronized, driver = _stage_executor(
                arm="left",
                trajectory=left_anchor_outbound,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                left_anchor_outbound,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(LEFT_ARM_INDICES)] = np.asarray(left_anchor_outbound.command_q_rad[-1])
            q14[:7] = np.asarray(left_anchor_outbound.command_q_rad[-1])
            _stop_driver(driver, guard)
            driver = None

            raw = PoseExecutor(
                transport=transport,
                clock=SystemClock(),
                pose_set=pose_sets[initial_arm],
                handoff_q=anchor_q29[np.asarray(arm_indices(initial_arm))],
                hold_q=anchor_q29[np.asarray(arm_indices(opposite_arm(initial_arm)))],
                approved_validation_report_sha256=plan.content_sha256,
                config=control_config,
                gravity_feedforward=gravity,
            )
            synchronized = SynchronizedPoseExecutor(raw)
            synchronized.adopt_owned_control(previous_command_q14=q14)
            driver = ExecutorControlDriver(
                synchronized,
                rate_hz=rate_hz,
                safety_heartbeat=_finger_heartbeat(guard, dex_controller),
            )
            driver.start()
            _wait_ready(
                synchronized,
                driver,
                timeout_s=control_config.acquisition_ramp_s + 5.0,
                label="bilateral visual-anchor handoff",
            )

            progress = {"message": "starting", "accepted": 0, "retries": 0}
            graceful_stop = {"requested": False}
            capture_count = sum(item.capturable for item in design.schedule)

            def poll_graceful_stop_key() -> None:
                if args.no_window:
                    return
                key = cv2.waitKey(1) & 0xFF
                if key not in {ord("q"), ord("Q")}:
                    return
                if not graceful_stop["requested"]:
                    print(
                        "Q RECEIVED — finishing at the next repeated anchor, then "
                        "returning to Ready",
                        flush=True,
                    )
                graceful_stop["requested"] = True
                progress["message"] = "Q REQUESTED — CERTIFIED RETURN PENDING"

            def preview(frame, detections, reports) -> None:
                if args.no_window:
                    return
                rendered = _render_bilateral_preview(
                    frame.image_bgr,
                    detections,
                    reports,
                    footer=(
                        f"{progress['message']} | {synchronized.state.value.upper()}",
                        (
                            f"ACCEPTED {progress['accepted']}/{capture_count}  "
                            f"RETRIES {progress['retries']}"
                        ),
                        "Q: FINISH SAFELY | CTRL+C: DAMP",
                    ),
                )
                cv2.imshow("G1 Dex3 bilateral calibration", rendered)
                poll_graceful_stop_key()

            def wait_once(duration_s: float) -> None:
                rclpy.spin_once(node, timeout_sec=0.0)
                poll_graceful_stop_key()
                driver.check()
                time.sleep(duration_s)

            source = BilateralLiveBurstSource(
                camera_frames=camera.frames,
                robot_states=states,
                detectors=detectors,
                quality_evaluators=evaluators,
                recording_config=recording,
                pairing_config=pairing,
                config=LiveBurstConfig(
                    frame_count=thresholds.stationary_burst_frames,
                    timeout_s=args.burst_timeout_s,
                    poll_interval_s=1.0 / rate_hz,
                    maximum_duration_s=thresholds.stationary_burst_maximum_duration_s,
                ),
                wait_once=wait_once,
                accept_yellow=lambda _frame, _sides: True,
                preview=preview,
                cancelled=lambda: graceful_stop["requested"],
            )

            def report(message: str, accepted: int, retries: int) -> None:
                progress.update(message=message, accepted=accepted, retries=retries)
                print(
                    f"{message}; accepted={accepted}/{capture_count}, retries={retries}",
                    flush=True,
                )

            maximum_transition_duration_s = max(
                transition.trajectory.sample_time_s[-1] for transition in plan.transitions
            )
            isolated_store.set_health_check(lambda: wait_once(0.0))
            orchestrator = BilateralCollectionOrchestrator(
                executor=synchronized,
                design=design,
                plan=plan,
                pose_sets=pose_sets,
                store=isolated_store,
                frame_source=source,
                wait_until_ready=lambda: _wait_ready(
                    synchronized,
                    driver,
                    timeout_s=max(
                        control_config.motion_timeout_s,
                        maximum_transition_duration_s,
                    )
                    + 5.0,
                    label="bilateral calibration trajectory",
                ),
                graceful_stop_requested=lambda: graceful_stop["requested"],
                maximum_capture_attempts=args.maximum_capture_attempts,
                report_progress=report,
            )
            result = orchestrator.run()
            _stop_driver(driver, guard)
            driver = None

            left_anchor_return = _stage_trajectory(adapter.left_anchor_return)
            synchronized, driver = _stage_executor(
                arm="left",
                trajectory=left_anchor_return,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                left_anchor_return,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(LEFT_ARM_INDICES)] = np.asarray(left_anchor_return.command_q_rad[-1])
            q14[:7] = np.asarray(left_anchor_return.command_q_rad[-1])
            _stop_driver(driver, guard)
            driver = None

            right_anchor_return = _stage_trajectory(adapter.right_anchor_return)
            synchronized, driver = _stage_executor(
                arm="right",
                trajectory=right_anchor_return,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                right_anchor_return,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(RIGHT_ARM_INDICES)] = np.asarray(right_anchor_return.command_q_rad[-1])
            q14[7:] = np.asarray(right_anchor_return.command_q_rad[-1])
            return_hand_q = {
                side: getattr(adapter_request.snapshot, f"{side}_dex3_q_rad") for side in _SIDES
            }
            restored = _command_validated_finger_posture(
                synchronized=synchronized,
                driver=driver,
                controller=dex_controller,
                planner=planner,
                joint_position_offsets_rad=plan.joint_position_offsets_rad,
                body_tolerance_rad=control_config.ownership_transition_position_tolerance_rad,
                hand_tolerance_rad=dex_config_value.posture_position_tolerance_rad,
                artifact_directory=session_directory / "runtime",
                phase="loaded_restore",
                left_target_q_rad=return_hand_q["left"],
                right_target_q_rad=return_hand_q["right"],
                left_acceptance_q_rad=return_hand_q["left"],
                right_acceptance_q_rad=return_hand_q["right"],
                label="restore measured starting bilateral hand posture",
            )
            return_error = _hand_posture_error_rad(restored, return_hand_q)
            if return_error > dex_config_value.posture_position_tolerance_rad:
                raise RuntimeError(f"settled Dex3 restoration error is {return_error:.4f}rad")
            _stop_driver(driver, guard)
            driver = None

            left_return = _stage_trajectory(adapter.preparation.left_return)
            synchronized, driver = _stage_executor(
                arm="left",
                trajectory=left_return,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                left_return,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(LEFT_ARM_INDICES)] = np.asarray(left_return.command_q_rad[-1])
            q14[:7] = np.asarray(left_return.command_q_rad[-1])
            _stop_driver(driver, guard)
            driver = None

            right_return = _stage_trajectory(adapter.preparation.right_return)
            synchronized, driver = _stage_executor(
                arm="right",
                trajectory=right_return,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            _execute_stage(
                synchronized,
                driver,
                right_return,
                plan_sha256=adapter.content_sha256,
                timeout_s=control_config.motion_timeout_s,
            )
            q29[np.asarray(RIGHT_ARM_INDICES)] = np.asarray(right_return.command_q_rad[-1])
            q14[7:] = np.asarray(right_return.command_q_rad[-1])
            _stop_driver(driver, guard)
            driver = None

            synchronized, driver = _stage_executor(
                arm="right",
                trajectory=None,
                q29=q29,
                q14=q14,
                model=model,
                transport=transport,
                gravity=gravity,
                control_config=control_config,
                plan_sha256=adapter.content_sha256,
                acquire=False,
                heartbeat=_finger_heartbeat(guard, dex_controller),
                rate_hz=rate_hz,
            )
            synchronized.begin_clean_release(operator_confirmed=True)
            deadline = time.monotonic() + control_config.release_ramp_s + 5.0
            while synchronized.state is not ExecutorState.STOPPED:
                driver.check()
                if time.monotonic() >= deadline:
                    raise RuntimeError("clean bilateral arm_sdk release timed out")
                time.sleep(0.01)
            _stop_driver(driver, guard)
            driver = None
            dex_controller.timeout()
            guard.disarm()
            synchronized.confirm_external_takeover(
                "clean bilateral arm_sdk weight-zero release completed"
            )
            status = {
                "status": "stopped_safely" if result.stopped_early else "completed",
                "commands_robot": True,
                "session": str(session_directory),
                "pose_design_sha256": design.content_sha256,
                "execution_plan_sha256": plan.content_sha256,
                "adapter_plan_sha256": adapter.content_sha256,
                "accepted": result.accepted_count,
                "rejected": result.rejected_count,
                "retries": result.retry_count,
                "attempted": result.attempted_count,
                "stopped_early": result.stopped_early,
                "return_anchor_occurrence_id": result.return_anchor_occurrence_id,
                "session_finalized": result.session_finalized,
                "collection_complete": (not result.stopped_early and result.rejected_count == 0),
                "terminal_action": guard.terminal_action,
            }
            outcome = (
                "STOPPED SAFELY AT LIVE READY"
                if result.stopped_early
                else "PASSED"
                if result.rejected_count == 0
                else "COMPLETE WITH REJECTIONS"
            )
            print(
                f"BILATERAL CALIBRATION COLLECTION {outcome} — finalized "
                f"{session_directory}; accepted={result.accepted_count}, "
                f"rejected={result.rejected_count}, retries={result.retry_count}",
                flush=True,
            )
        finally:
            if not args.no_window:
                cv2.destroyAllWindows()
            if "node" in locals():
                if camera is not None:
                    camera.close()
                    camera = None
                node.destroy_node()
            if "rclpy" in locals() and rclpy.ok():
                rclpy.shutdown()
    except BaseException as error:
        status = {
            "status": "failed",
            "commands_robot": bool(
                (transport is not None and transport.command_count)
                or (dex_controller is not None and dex_controller.command_count)
            ),
            "error_type": type(error).__name__,
            "error": str(error),
            "session": str(session_directory),
        }
        raise
    finally:
        cleanup_errors: list[str] = []
        if driver is not None and driver.is_alive:
            try:
                driver.close()
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"driver: {error}")
        if dex_controller is not None and not dex_controller.timed_out:
            try:
                dex_controller.timeout()
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"Dex3 timeout: {error}")
        if guard is not None and guard.armed:
            try:
                if transport is None or transport.command_count == 0:
                    guard.disarm()
                else:
                    guard.damp("bilateral calibration failed or was interrupted")
                    if synchronized is not None:
                        synchronized.confirm_external_damping(
                            "PC2 verified Damp after bilateral calibration failure"
                        )
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"PC2 safety: {error}")
        if dex_controller is not None:
            try:
                if not dex_controller.timed_out and guard is not None and guard.terminal_action:
                    dex_controller.close_after_external_timeout()
                else:
                    dex_controller.close()
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"Dex3 close: {error}")
        for name, value in (("lowstate observer", observer), ("Dex3 observer", dex_observer)):
            if value is not None:
                try:
                    value.close()
                except BaseException as error:  # noqa: BLE001
                    cleanup_errors.append(f"{name}: {error}")
        if transport is not None and transport.command_count == 0:
            try:
                transport.close()
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"transport: {error}")
        if planner is not None:
            try:
                planner.close()
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"planner: {error}")
        if isolated_store is not None:
            try:
                isolated_store.close()
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"capture writer: {error}")
        command_lock.release()
        if raw_recorder is not None and (raw_recorder.started or raw_recorder.summary is not None):
            try:
                status["recording"] = raw_recorder.stop()
                print(f"RAW RECORDING SAVED — {raw_recorder.bag_directory}", flush=True)
            except BaseException as error:  # noqa: BLE001
                cleanup_errors.append(f"raw episode recorder: {error}")
                status["recording"] = {
                    "state": "finalization_failed",
                    "complete": False,
                    "episode_directory": str(raw_recorder.episode_directory),
                    "error": str(error),
                }
        status["cleanup_errors"] = cleanup_errors
        try:
            status_path.write_text(json.dumps(status, indent=2, sort_keys=True) + "\n")
        except OSError:
            pass
    print(json.dumps(status, indent=2, sort_keys=True))
    return 0
